### PR TITLE
Updated website map visuals

### LINKED ISSUE #453: Map layout on mobile is very broken
image

- Make a copy of the start stop buttons, place it underneath the capture information.
- Hide the first start stop on xs viewpoint 
- Make the capture information full width on mobile
- Make the copy of start stop half width on xs breakpoint
- Make the slider half width on xs breakpoint

### PR DESCRIPTION
**Pull request by oslohes123**
Added a new responsive set of buttons that are mobile first
These buttons will disappear in the desktop but re-appear on the mobile space
The desktop layout is kept for ipads which is fine since they work ok
fixes #453

### CODE REVIEW

**Comment by oslohes123** [comment]
Also have I done the fixes #number correctly I was told to do that on some forums cause apparently it's supposed to make a pr automatically but it didn't so I made one anyway

**Comment by Maelstromeous** [comment]
It doesn't make s PR but it does close the issue. 

Can we have screenshots at the desktop and the mobile breakpoints please

**Comment by oslohes123** [comment]
> It doesn't make s PR but it does close the issue.
> 
> Can we have screenshots at the desktop and the mobile breakpoints please

Ah I see when you say close the issue what do you mean by that?
On desktop:
image

On iphone
image

**Comment by oslohes123** [comment]
I just read the comments on discord I'll try to make the slider as long as possible and see if I can fix the toggle as well

**Comment by oslohes123** [comment]
Now I have fixed the toggle by simply making it span full, on mobile and then on desktop it will be re-arranged to the standard look
On iphone 11 it will look like this 
image

**Comment by Maelstromeous** [comment]
Perfect, if you're able to make the slider longer then I'll approve this

**Comment by Maelstromeous** [comment]
> Ah I see when you say close the issue what do you mean by that?

When you use "fixes #1234" or "closes #1234" in either a vomit message or the PR description itself when the PR is merged it'll close the referenced issue. Google Github Smart Commits for more info b

**Comment by oslohes123** [comment]
> Perfect, if you're able to make the slider longer then I'll approve this

How about this?
image

**Review by Maelstromeous — DISMISSED** [review]

**Comment by oslohes123** [comment]
Hold on
I haven't pushed the changes yet

**Review by Maelstromeous — APPROVED** [review]

**Pull request merged**
